### ISSUE TITLE
rufus-scheduler ~> 3.0

### ISSUE THREAD

**Issue by jmettraux** [bibendi/schked#2]
Hello,

I am curious, why is Schked using [rufus-scheduler](https://github.com/jmettraux/rufus-scheduler) 3.0.x (2014) instead of the current [3.5.x](https://rubygems.org/gems/rufus-scheduler) (2018)?

Thanks in advance and best regards.

**Comment by bibendi** [comment]
Hey!

Sorry for the late response, I missed up this issue =(

Schked can use all 3.x versions. You can make sure about this if you open `schked.gemspec`.
