### ISSUE TITLE
Fails to start when there is no `config/schedule.rb`

### ISSUE THREAD

**Issue by palkan** [bibendi/schked#9]
There could be no `schedule.rb` in the main Rails app (but in engines).

Now it fails with:

```
bundler: failed to load command: schked (/app/vendor/bundle/ruby/2.6.0/bin/schked)
Errno::ENOENT: No such file or directory @ rb_sysopen - /app/config/schedule.rb
/app/vendor/bundle/ruby/2.6.0/gems/schked-0.2.1/lib/schked/worker.rb:35:in `read'
```

Temporary salutation is to add an empty `schedule.rb` file.

**Comment by bibendi** [comment]
@palkan, please, take a look on this https://github.com/bibendi/schked/pull/10
